/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colloques.ihm;

import javax.swing.Box;

/**
 *
 * @author florent
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        AccueilPanel accPanel = new AccueilPanel();
        this.setSize((int) accPanel.getPreferredSize().getWidth(), (int) accPanel.getPreferredSize().getHeight());
        this.add(accPanel);

        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Fichier = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        importCSV = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Ajouter = new javax.swing.JMenu();
        ajoutEven = new javax.swing.JMenuItem();
        ajoutPart = new javax.swing.JMenuItem();
        ajoutPartEven = new javax.swing.JMenuItem();
        modif = new javax.swing.JMenu();
        modifEven = new javax.swing.JMenuItem();
        modifPart = new javax.swing.JMenuItem();
        consulter = new javax.swing.JMenu();
        consulterEven = new javax.swing.JMenuItem();
        consulterPart = new javax.swing.JMenuItem();
        supprimer = new javax.swing.JMenu();
        supprimerEven = new javax.swing.JMenuItem();
        supprimerPart = new javax.swing.JMenuItem();
        deconnexion = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colloques");
        setMinimumSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(null);

        Fichier.setText("Fichier");

        jMenuItem2.setText("Accueil");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Fichier.add(jMenuItem2);

        importCSV.setText("Import CSV");
        importCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importCSVActionPerformed(evt);
            }
        });
        Fichier.add(importCSV);

        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Fichier.add(jMenuItem1);

        jMenuBar1.add(Fichier);

        Ajouter.setText("Ajouter");

        ajoutEven.setText("Ajouter un événement");
        ajoutEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutEvenActionPerformed(evt);
            }
        });
        Ajouter.add(ajoutEven);

        ajoutPart.setText("Ajouter un participant");
        ajoutPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutPartActionPerformed(evt);
            }
        });
        Ajouter.add(ajoutPart);

        ajoutPartEven.setText("Ajouter un participant à un événement");
        ajoutPartEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutPartEvenActionPerformed(evt);
            }
        });
        Ajouter.add(ajoutPartEven);

        jMenuBar1.add(Ajouter);

        modif.setText("Modifier");

        modifEven.setText("Modifier un événement");
        modifEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifEvenActionPerformed(evt);
            }
        });
        modif.add(modifEven);

        modifPart.setText("Modifier un participant");
        modifPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifPartActionPerformed(evt);
            }
        });
        modif.add(modifPart);

        jMenuBar1.add(modif);

        consulter.setText("Consulter");

        consulterEven.setText("Consulter les événements");
        consulterEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterEvenActionPerformed(evt);
            }
        });
        consulter.add(consulterEven);

        consulterPart.setText("Consulter les participants");
        consulterPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterPartActionPerformed(evt);
            }
        });
        consulter.add(consulterPart);

        jMenuBar1.add(consulter);

        supprimer.setText("Supprimer");

        supprimerEven.setText("Supprimer un événement");
        supprimerEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEvenActionPerformed(evt);
            }
        });
        supprimer.add(supprimerEven);

        supprimerPart.setText("Supprimer un participant");
        supprimerPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerPartActionPerformed(evt);
            }
        });
        supprimer.add(supprimerPart);

        jMenuBar1.add(supprimer);

        jMenuBar1.add(Box.createHorizontalGlue());
        deconnexion.setText("Déconnexion");
        deconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Deconnexion(evt);
            }
        });
        jMenuBar1.add(deconnexion);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Deconnexion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deconnexion
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_Deconnexion
    
    private void ajoutPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutPartActionPerformed
        SaisieParticipantPanel saisiePartici = new SaisieParticipantPanel();
        this.setContentPane(saisiePartici);
        this.repaint();
        this.revalidate();
        this.setSize((int) saisiePartici.getPreferredSize().getWidth(), (int) saisiePartici.getPreferredSize().getHeight());
    }//GEN-LAST:event_ajoutPartActionPerformed

    private void ajoutEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutEvenActionPerformed
        SaisieEventPanel saisieEvent = new SaisieEventPanel();
        this.setContentPane(saisieEvent);
        this.repaint();
        this.revalidate();
        this.setSize((int) saisieEvent.getPreferredSize().getWidth(), (int) saisieEvent.getPreferredSize().getHeight()+70);
    }//GEN-LAST:event_ajoutEvenActionPerformed

    private void importCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importCSVActionPerformed
        ImportParticipants impEvent = new ImportParticipants();
        this.setContentPane(impEvent);
        this.repaint();
        this.revalidate();
        this.setSize((int) impEvent.getPreferredSize().getWidth(), (int) impEvent.getPreferredSize().getHeight());
    }//GEN-LAST:event_importCSVActionPerformed

    private void consulterEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterEvenActionPerformed
        ConsulterEventPanel consulterEvent = new ConsulterEventPanel();
        this.setContentPane(consulterEvent);
        this.repaint();
        this.revalidate();
        this.setSize((int) consulterEvent.getPreferredSize().getWidth(), (int) consulterEvent.getPreferredSize().getHeight());
    }//GEN-LAST:event_consulterEvenActionPerformed

    private void consulterPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterPartActionPerformed
        ConsulterParticipantPanel consulterPartici = new ConsulterParticipantPanel();
        this.setContentPane(consulterPartici);
        this.repaint();
        this.revalidate();
        this.setSize((int) consulterPartici.getPreferredSize().getWidth(), (int) consulterPartici.getPreferredSize().getHeight());
    }//GEN-LAST:event_consulterPartActionPerformed

    private void modifEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifEvenActionPerformed
        ModifierEventPanel modifierEvent = new ModifierEventPanel();
        this.setContentPane(modifierEvent);
        this.repaint();
        this.revalidate();
        this.setSize((int) modifierEvent.getPreferredSize().getWidth(), (int) modifierEvent.getPreferredSize().getHeight());
    }//GEN-LAST:event_modifEvenActionPerformed

    private void supprimerEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEvenActionPerformed
        SupprimerEventPanel supprimerEvent = new SupprimerEventPanel();
        this.setContentPane(supprimerEvent);
        this.repaint();
        this.revalidate();
        this.setSize((int) supprimerEvent.getPreferredSize().getWidth(), (int) supprimerEvent.getPreferredSize().getHeight());
    }//GEN-LAST:event_supprimerEvenActionPerformed

    private void supprimerPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerPartActionPerformed
        SupprimerParticipantPanel supprimerPartici = new SupprimerParticipantPanel();
        this.setContentPane(supprimerPartici);
        this.repaint();
        this.revalidate();
        this.setSize((int) supprimerPartici.getPreferredSize().getWidth(), (int) supprimerPartici.getPreferredSize().getHeight());
    }//GEN-LAST:event_supprimerPartActionPerformed

    private void ajoutPartEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutPartEvenActionPerformed
        AjouterPartEven a = new AjouterPartEven();
        this.setContentPane(a);
        this.repaint();
        this.revalidate();
        this.setSize((int) a.getPreferredSize().getWidth(), (int) a.getPreferredSize().getHeight());
    }//GEN-LAST:event_ajoutPartEvenActionPerformed

    private void modifPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifPartActionPerformed
        ModifierParticipantPanel modifierPart = new ModifierParticipantPanel();
        this.setContentPane(modifierPart);
        this.repaint();
        this.revalidate();
        this.setSize((int) modifierPart.getPreferredSize().getWidth(), (int) modifierPart.getPreferredSize().getHeight());
    }//GEN-LAST:event_modifPartActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          AccueilPanel accPanel = new AccueilPanel();
         this.setContentPane(accPanel);
        this.repaint();
        this.revalidate();
        this.setSize((int) accPanel.getPreferredSize().getWidth(), (int) accPanel.getPreferredSize().getHeight());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ajouter;
    private javax.swing.JMenu Fichier;
    private javax.swing.JMenuItem ajoutEven;
    private javax.swing.JMenuItem ajoutPart;
    private javax.swing.JMenuItem ajoutPartEven;
    private javax.swing.JMenu consulter;
    private javax.swing.JMenuItem consulterEven;
    private javax.swing.JMenuItem consulterPart;
    private javax.swing.JMenu deconnexion;
    private javax.swing.JMenuItem importCSV;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu modif;
    private javax.swing.JMenuItem modifEven;
    private javax.swing.JMenuItem modifPart;
    private javax.swing.JMenu supprimer;
    private javax.swing.JMenuItem supprimerEven;
    private javax.swing.JMenuItem supprimerPart;
    // End of variables declaration//GEN-END:variables
}
