/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colloques.ihm;

import colloques.classesMetier.Evenement;
import colloques.classesMetier.Salle;
import colloques.dao.EvenementDAO;
import colloques.dao.SalleDAO;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author florent
 */
public class SaisieEventPanel extends javax.swing.JPanel {

    /**
     * Creates new form SaisieEventPanel
     */
    public SaisieEventPanel() {
        initComponents();
        
        //Min date debut
        GregorianCalendar gcMinDate = new GregorianCalendar();
        dateChooserDebut.setMinDate(gcMinDate);    //OK
        
        //Select date debut par defaut
        GregorianCalendar gcCurrentDeb = new GregorianCalendar();
        gcCurrentDeb.add(Calendar.DATE, 1);
        dateChooserDebut.setSelectedDate(gcCurrentDeb);
        
        Calendar gcMinFin = dateChooserDebut.getSelectedDate();
        gcMinFin.add(Calendar.DATE, -1);
        dateChooserFin.setMinDate(gcMinFin); //OK
        dateChooserFin.setSelectedDate(gcCurrentDeb);
        //dateChooserFin.setCurrent(gc);
        
        //Populé la liste des salles
        SalleDAO salleDAO = new SalleDAO();
        List<Salle> salles = salleDAO.getALL();
        List<String> nomSalles = new ArrayList<String>();
        
        for(Salle salle : salles) {
            nomSalles.add(salle.getNom());
        }
        comboNomSalle.setModel(new DefaultComboBoxModel(nomSalles.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonInsertEvent = new javax.swing.JButton();
        txtLibelle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinNbrParticipant = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateChooserDebut = new datechooser.beans.DateChooserCombo();
        dateChooserFin = new datechooser.beans.DateChooserCombo();
        lblTitre = new javax.swing.JLabel();
        txtTheme = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spinDuree = new javax.swing.JSpinner();
        txtOrganisateur = new javax.swing.JTextField();
        txtTypeEvenement = new javax.swing.JTextField();
        comboNomSalle = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        BoutonInsertEvent.setText("Insérer l'événement");
        BoutonInsertEvent.setActionCommand("Insérer l'évènement");
        BoutonInsertEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonInsertEventActionPerformed(evt);
            }
        });

        jLabel1.setText("Libellé");
        jLabel1.setToolTipText("");

        jLabel2.setText("Thème");
        jLabel2.setToolTipText("");

        jLabel3.setText("Nombres de participant maximum");

        spinNbrParticipant.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setText("Description");

        jScrollPane1.setViewportView(txtDescription);

        jLabel5.setText("Organisateur");

        jLabel6.setText("Type d'événement");

        jLabel8.setText("Nom de salle");

        dateChooserDebut.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserDebut.setCalendarPreferredSize(new java.awt.Dimension(340, 240));
    dateChooserDebut.setNothingAllowed(false);

    dateChooserFin.setCalendarPreferredSize(new java.awt.Dimension(340, 240));

    lblTitre.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
    lblTitre.setText("Création d'un évènement");

    jLabel10.setText("Durée");
    jLabel10.setToolTipText("");

    spinDuree.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

    txtTypeEvenement.setToolTipText("");

    comboNomSalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "md4", "Claude", "Abrham", "Lincoln" }));

    jLabel11.setText("Date de début");

    jLabel12.setText("Date de fin");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLibelle, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(txtTheme, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(dateChooserDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateChooserFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(spinDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spinNbrParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboNomSalle, 0, 196, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTypeEvenement)
                                .addComponent(txtOrganisateur)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGap(20, 20, 20))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BoutonInsertEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(lblTitre)
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(dateChooserDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12))
                        .addComponent(dateChooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(spinDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(spinNbrParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(txtOrganisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtTypeEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(comboNomSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addComponent(BoutonInsertEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        this.setSize(this.getParent().getSize());
    }//GEN-LAST:event_formAncestorResized

    private void BoutonInsertEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonInsertEventActionPerformed

        //Get numéro de salle
        int numSalle;
        
        SalleDAO salleDAO = new SalleDAO();
        numSalle = salleDAO.recupNumSalle(comboNomSalle.getSelectedItem().toString());
        
        //Check numSalle
        if(numSalle < 0)
        {
            JOptionPane.showMessageDialog(this, "Erreur numéro de salle.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        Evenement event = new Evenement(
            txtLibelle.getText().trim(), txtTheme.getText().trim(),
            (GregorianCalendar)dateChooserDebut.getSelectedDate(), (GregorianCalendar)dateChooserFin.getSelectedDate(),
            spinDuree.getValue().hashCode(), spinNbrParticipant.getValue().hashCode(),
            txtDescription.getText().trim(), txtOrganisateur.getText().trim(),
            txtTypeEvenement.getText().trim(), "À venir", numSalle
        );
        
        //Envoye
        EvenementDAO eventDAO = new EvenementDAO();
        Calendar c = Calendar.getInstance ();
        Date date = c.getTime ();
            
        boolean estapresdebut = dateChooserDebut.getSelectedDate().getTime().after(date);
        boolean estapresfin = dateChooserFin.getSelectedDate().getTime().after(date);
        boolean estaprsdate = dateChooserFin.getSelectedDate().getTime().after(dateChooserDebut.getSelectedDate().getTime());
            
        if(!estapresdebut)
        {
            JOptionPane.showMessageDialog(this, "La date de début doit être supérieur à la date actuelle.");
        }
        else if(!estapresfin)
        {
            JOptionPane.showMessageDialog(this, "La date de fin doit être supérieur à la date actuelle.");
        }
        else if(!estaprsdate)
        {
            JOptionPane.showMessageDialog(this, "La date de fin doit être supérieur à la date de début.");
        }
        else if(eventDAO.create(event))
        {
            JOptionPane.showMessageDialog(this, "L'événement a bien été enregistré.");
        }else
        {
            JOptionPane.showMessageDialog(this, "L'événement n'a pas pu ètre enregistré.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BoutonInsertEventActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonInsertEvent;
    private javax.swing.JComboBox comboNomSalle;
    private datechooser.beans.DateChooserCombo dateChooserDebut;
    private datechooser.beans.DateChooserCombo dateChooserFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JSpinner spinDuree;
    private javax.swing.JSpinner spinNbrParticipant;
    private javax.swing.JTextPane txtDescription;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtOrganisateur;
    private javax.swing.JTextField txtTheme;
    private javax.swing.JTextField txtTypeEvenement;
    // End of variables declaration//GEN-END:variables
}
